import type { NextPage } from "next";
import Head from "next/head";
import dynamic from "next/dynamic";
import { useSyncMessages } from "../lib/web/board/useSyncMessages";

const GridNoSSr = dynamic(() => import("../lib/web/board/Grid"), {
  ssr: false,
});

const Board: NextPage = () => {
  useSyncMessages();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GridNoSSr />
    </>
  );
};

export default Board;
